#链接种子集合
capture:
  seeds:
    - http://www.bxd365.com/agent             #保险岛
    - http://www.axbxw.com/agent              #爱心保险
    - http://www.dajiabao.com/guwen           #大家保
    - http://www.life-sky.net/                #保险中间站
    - http://member.vobao.com/                #沃保网
    - http://a.xiangrikui.com/                #向日葵
    - http://www.yibaobx.com/agent-1.html     #益保保险